cabal-version: 3.14

name:           fine-compiler
version:        0.1.0.0
description:    Please see the README on GitHub at <https://github.com/egmaleta/fine-compiler#readme>
homepage:       https://github.com/egmaleta/fine-compiler#readme
bug-reports:    https://github.com/egmaleta/fine-compiler/issues
author:         Eduardo García Maleta
maintainer:     egmaleta@proton.me
copyright:      2024 Eduardo García Maleta
license:        BSD-3-Clause
license-file:   LICENSE
build-type:     Simple
extra-source-files:
  README.md
  CHANGELOG.md

source-repository head
  type: git
  location: https://github.com/egmaleta/fine-compiler

common options
  ghc-options: -Wall
  default-language: GHC2024

library
  import:
    options
  exposed-modules:
    Control.Monad.ErrorCollector
    Control.Monad.Trans.REC
    Control.Monad.Trans.RS
    Control.Monad.Trans.RW
    Control.Monad.Trans.SEC
    Control.Monad.Trans.SW
    Data.Errors
    Data.List.Extra
    Data.List.NonEmpty.Extra
    Data.Tuple.Extra
    Fine.Codegen.Js
    Fine.Codegen.Ready
    Fine.Codegen.Rename
    Fine.Codegen.TailRec
    Fine.Codegen.Wasm
    Fine.Error
    Fine.Lexer
    Fine.Parser
    Fine.Syntax
    Fine.Syntax.Utils
    Fine.Transform
    Fine.Transform.Expr
    Fine.Transform.Type
    Fine.Transform.Vars
  hs-source-dirs:
    src
  default-extensions:
    InstanceSigs
    StrictData
    OverloadedStrings
    MultiParamTypeClasses
    FlexibleContexts
    FlexibleInstances
    QuasiQuotes
    DataKinds
    KindSignatures
    TypeFamilies
  build-depends:
    array,
    base >=4.7 && <5,
    containers,
    string-interpolate,
    text,
    text-ansi,
    transformers

executable fine-compiler
  import:
    options
  main-is:
    Main.hs
  hs-source-dirs:
    app
  default-extensions:
    InstanceSigs
    StrictData
    OverloadedStrings
    MultiParamTypeClasses
    FlexibleContexts
    FlexibleInstances
    QuasiQuotes
    DataKinds
    KindSignatures
    TypeFamilies
  build-depends:
    base >=4.7 && <5,
    containers,
    string-interpolate,
    text,
    text-ansi,
    transformers,
    fine-compiler

test-suite fine-compiler-test
  import:
    options
  type:
    exitcode-stdio-1.0
  main-is:
    Spec.hs
  hs-source-dirs:
    test
  default-extensions:
    InstanceSigs
    StrictData
    OverloadedStrings
    MultiParamTypeClasses
    FlexibleContexts
    FlexibleInstances
    QuasiQuotes
    DataKinds
    KindSignatures
    TypeFamilies
