name:                fine-compiler
version:             0.1.0.0
github:              "egmaleta/fine-compiler"
license:             BSD-3-Clause
author:              "Eduardo García Maleta"
maintainer:          "egmaleta@proton.me"
copyright:           "2024 Eduardo García Maleta"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/egmaleta/fine-compiler#readme>

dependencies:
- base >= 4.7 && < 5
- array
- containers
- string-interpolate
- text
- text-ansi
- transformers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
- InstanceSigs
- StrictData
- OverloadedStrings
- MultiParamTypeClasses
- FlexibleContexts
- FlexibleInstances
- QuasiQuotes

library:
  source-dirs: src

executables:
  fine-compiler-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fine-compiler

tests:
  fine-compiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fine-compiler
